### ISSUE TITLE
using promise structure, will help to use methods in transactions

### ISSUE THREAD

**Issue by cybercoder** [KaveNegar/kavenegar-node#1]
In a case, needed to store new user data in to postgresql database, only when to be sure the SMS message sent, Obviously, i needed to use Transactions.
so i did paint "VerifyLookup" method to act as a promise.

This is my code:
```javascript
function promisify(r,t,tpl) {
    return new Promise(function (resolve, reject) {
		kapi.VerifyLookup({
			receptor: r,
			token : t,
			template : tpl
		},
		function(response, status) {
			if (status==200)
				resolve(response) ;
			else
				reject(status) ;
		});
    });
}
```

and in express router by using "sequelize" as ORM and "bcrypt" as hash man:
```javascript
router.post('/register',function(req,res,next){
	var num = Math.floor(Math.random() * 9000) + 1000;
		bcrypt.genSalt(saltRounds, function(err, salt) {
			bcrypt.hash(req.body.password, salt, function(err, hash) {
				req.body.password = hash ;
				req.body.verificationCode = num ;
				req.body.RoleId = 1 ;
				models.sequelize.transaction(function (t) {
					return models.User.create(req.body, {transaction: t}).then(function(result){
						// send verification code via sms
						return promisify(result.dataValues.mobilePhone,num,'MyTemplate').then(function(status){
							res.status(200).json('Ok') ;
						}).catch(function(e) {
							throw Error(e) ;
						});
						
					})
				}).catch(function(error){
					res.status(500).json(error) ;
				});
			});
		});

});
```
So, you can try promise structure in next versions of API.

Regards.

**Comment by bgsrb** [comment]
Thank you.
This case will be considered in the next releases.

**Comment by cybercoder** [comment]
The point is Sequelize Transaction will rollback automatically when a chain in promise(es) structure get fail.

**Comment by ghonchesefidi** [comment]
Good Idea. Hope they implement it in the next releases. Currently, I'm using Axios and handling error cases using Axios callbacks.

**Comment by cybercoder** [comment]
> Good Idea. Hope they implement it in the next releases. Currently, I'm using Axios and handling error cases using Axios callbacks.

Yep,
But you can make a promise yourself like which i did in old syntax.
